version: "3"

services:
  # Pihole - ad blocker
  # https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "${PIHOLE_PORT}:80/tcp"
    environment:
      TZ: "${TIMEZONE}"
      WEBPASSWORD: "${COMMON_PASSWORD}"
    # Volumes store your data between container upgrades
    volumes:
      - './data/pihole/etc-pihole:/etc/pihole'
      - './data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    restart: unless-stopped