version: "3"

services:
  # Pihole - ad blocker
  # https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "${PIHOLE_PORT}:80/tcp"
    environment:
      TZ: "${TIMEZONE}"
      WEBPASSWORD: "${COMMON_PASSWORD}"
    # Volumes store your data between container upgrades
    volumes:
      - './data/pihole/etc-pihole:/etc/pihole'
      - './data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    restart: unless-stopped

  # Portainer
  # https://docs.portainer.io/start/install/server/docker/linux
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "${PORTAINER_PORT}:9000"
    environment:
      TZ: "${TIMEZONE}"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/portainer/data:/data'    
    restart: unless-stopped

  # Dashy - service organizer
  # https://github.com/Lissy93/dashy/blob/master/docker-compose.yml
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./data/dashy/conf.yml:/app/public/conf.yml
    ports:
      - ${DASHY_PORT}:80
    environment:
      - NODE_ENV=production
      - UID=${UID}
      - GID=${GID}
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Glances - System monitor
  # https://glances.readthedocs.io/en/latest/docker.html
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    ports:
      - "${GLANCES_PORT}:61208"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
    restart: always